AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
  UseCache: false

Layout/LineLength:
  Max: 100
  AllowURI: true
  IgnoreCopDirectives: true
  IgnoredPatterns: ['\A\ *#']
  Exclude:
    - spec/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*
  ExcludedMethods:
    - state_machine
Style/NestedParenthesizedCalls:
  Exclude:
    - spec/**/*
Style/WordArray:
  Exclude:
    - spec/**/*
Style/NumericLiterals:
  Exclude:
    - spec/**/*
Security/Open:
  Exclude:
    - spec/**/*
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 15
Naming/PredicateName:
  Exclude:
    - app/graphql/**/*

Style/MultilineBlockChain:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/AccessModifierIndentation:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case
Lint/UriEscapeUnescape:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Migration/DepartmentName:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/DuplicateElsifCondition:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/ArrayCoercion:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: false
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/MissingSuper:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/StringConcatenation:
  Enabled: true

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes
Style/StringLiteralsInInterpolation:
  Description: Checks if uses of quotes inside expressions in interpolated strings
    match the configured preference.
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes

Layout/DotPosition:
  Description: Checks the position of the dot in multi-line method calls.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains
  Enabled: true
  EnforcedStyle: leading
  SupportedStyles:
  - leading
  - trailing

Style/CollectionMethods:
  Description: Preferred collection methods.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    find_all: select
    reduce: inject
    detect: find

Style/Lambda:
  EnforcedStyle: literal
